### ISSUE TITLE
cannot import InvalidSchemeCombination

### ISSUE THREAD

**Issue by Hilal-Urun** [JardinRyu/PedestrianCounter_Jetson#1]
Hi, when I tried to install requirements I got ;
`Import Error : cannot import InvalidSchemeCombination` errror and I searched it but I can not find any solution about it, could you help me? 
Python version : 3.6
Ubuntu version 18.4 and it says that latest pip version is 19. sth .

**Comment by JardinRyu** [comment]
I think you didn't follow the prerequisites.
