### ISSUE TITLE
hello! How to change people counting to detect and count other targets? Thanks for your guidance !

### ISSUE THREAD

**Issue by chenbinCBcau** [JardinRyu/PedestrianCounter_Jetson#2]

**Comment by JardinRyu** [comment]
If the target class you want is included in COCO, you can change the class number to detect on line 39 of utils/ssd.py.

**Comment by chenbinCBcau** [comment]
Thanks for your reply! But the target class I want, red ball and green ball, is not included in COCO dataset, so what should I solve it?

**Comment by chenbinCBcau** [comment]
The red/green ball is similar to ping pong. hahaha!

**Comment by JardinRyu** [comment]
I think you need to refer to https://jkjung-avt.github.io/hand-detection-tutorial/ to train your detector.

**Comment by chenbinCBcau** [comment]
ok, thanks very much! I will refer to it carefully.
